### ISSUE TITLE
Trim column headings when looking for matches in columns.csv

### ISSUE THREAD

**Issue by jennet** [Swirrl/table2qb#111]
A rogue whitespace character at the end of a column heading causes the cube-pipeline to error, but as the problem is whitespace it's not obvious what the problem is (as the column heading appears to match).

Possible workaround: column headings are trimmed of any whitespace before looking for a match

I can supply test files if necessary.

**Comment by Robsteranium** [comment]
I'm closing this now following the discussions in #115. Please see #122 for an alternative proposal to re-introduce this under a feature flag.
