### ISSUE TITLE
codelist pipeline CSVW should not generate ?scheme skos:member ?concept triples

### ISSUE THREAD

**Issue by jennet** [Swirrl/table2qb#118]
https://github.com/swirrl/table2qb/blob/log4j-config-fix/src/table2qb/pipelines/codelist.clj#L60

the skos:member predicate is only valid between a skos:Collection and skos:Concept. skos:Collection and skos:ConceptScheme are disjoint and so skos:member should not be created here

https://www.w3.org/TR/2008/WD-skos-reference-20080829/skos.html#member

**Comment by Robsteranium** [comment]
It looks like this is resolved with #119, thanks.
