### ISSUE TITLE
Plan for open-sourcing table2qb

### ISSUE THREAD

**Issue by Robsteranium** [Swirrl/table2qb#28]
1. Allow application to set configuration (as csv or SPARQL endpoint) #20 & #21
1. How to allow application to register transformations?
1. How to link `component->property-uri` and `columns.property_template` (user needs to know URI convention, can we make this explicit?)
1. Resolve performance issues #24, #26.
1. Split core into namespaces?
1. Review regional-trade example (perhaps use third-party codelist in place of the slugged services scheme)
1. Write a getting started doc

**Comment by RickMoynihan** [comment]
Is this done, given that the repo is public?
