### ISSUE TITLE
Output CSVW in standard mode within pipelines

### ISSUE THREAD

**Issue by lkitching** [Swirrl/table2qb#55]
Pipelines currently invoke csv2rdf in standard mode which includes statements about the table structure in the output RDF - specify minimal mode instead. In future, the output should be configurable.

**Comment by Robsteranium** [comment]
Could you expand a bit on that please - e.g. which properties would be lost and how are they used to configure dataset metadata?

**Comment by lkitching** [comment]
The [algorithm](https://www.w3.org/TR/2015/REC-csv2rdf-20151217/#generating-rdf) for generating RDF from the loaded metadata only outputs annotations in standard mode (see steps 3, 4.5 and 4.6.7). These are used in the generated metadata documents to specify dataset metadata, see [here](https://github.com/Swirrl/table2qb/blob/635caa9253966ef5f4d94ac79ec766771d19508c/src/table2qb/pipelines/cube.clj#L177) for example where the dataset title is configured. Common property annotations are not output in minimal mode so we can't use that. Standard mode also outputs the `csvw` metadata which we don't necessarily need, so I think we'd need a 'minimal-plus' mode which outputs the cell values as in minimal mode along with the annotations but without the `csvw` metadata about the table structure.
