### ISSUE TITLE
components.csv

### ISSUE THREAD

**Issue by PaulZH** [Swirrl/table2qb#61]
Based on the input csv I would define the configuration as follows.
```
Label,Description,Component Type,Codelist
Geography,Geographical reference Area,Dimension,
Quarter,Reference Period,Dimension,
Gender,The state of being male or female,Dimension,http://statistics.gov.scot/def/concept-scheme/gender
Measure Type,What is being measured,Dimension, 
### however doe not see how to indicate that this is the qb:measureType
Unit,Unit of Measurement,Attribute,
Value,Measured quantity,Measure,

```
In the example configuration.csv only Gender has been included.

How does the system know that geography and quarter are also dimensions?
What to do if the local URI standards are different from the uri pattern used over here e.g. having def# or ending with #id ?
What to do if one wants to use the sdmx dimension id's (refArea, refPeriod) instead of local ones?

Then the second line describes the values of the Measure Type dimension.
Does the conversion expect a fixed header 'Measure Type'?
What if your cube structure doesn't need a measure type?

Does the conversion expect a fixed header 'Value'? How does it know for the moment that this column contains the measured value?

**Comment by PaulZH** [comment]
I meanwhile discovered that the real column mappings happens in the --column-config, which answers some of the questions above.
So my configuration would end up:
```
Label,Description,Component Type,Codelist
Geography,Geographical reference Area,Dimension,
Quarter,Reference Period,Dimension,
Gender,The state of being male or female,Dimension,http://statistics.gov.scot/def/concept-scheme/gender
Unit,Unit of Measurement,Attribute,
Count,Total number of items, Measure
```

**Comment by PaulZH** [comment]
More insight.
The components.csv only needs to be completed for your own namespace(s).

It would be better to start the explanation with the main mapping (columns.csv), then the rest makes more sense.

**Comment by BillSwirrl** [comment]
thanks Paul - this is useful feedback on the documentation, as well as on whether things work correctly or predictably.  I'm just working through the details of the points you raised, to make sure I understand them properly
