### ISSUE TITLE
codelist-pipeline generates inconsistent data

### ISSUE THREAD

**Issue by PaulZH** [Swirrl/table2qb#70]
generates 
<http://example.org/def/concept-scheme/{cs} rdf:type skos:ConceptScheme;
skos:hasTopConcept <http://example.org/def/concept/{c}
skos:member <http://example.org/def/concept/{c}.

However the domain of skos:member is skos:Collection, which is defined as disjoint from skos:ConceptScheme.

**Comment by Robsteranium** [comment]
Ah yes, I didn't realise they were disjoint.

It looks like we should use `:concept skos:inScheme :scheme .` instead of `skos:member` (and traverse the relation the opposite way around).

**Comment by RickMoynihan** [comment]
Fixed in  PR #119
