### ISSUE TITLE
Greater configurability of URI patterns in generated data

### ISSUE THREAD

**Issue by BillSwirrl** [Swirrl/table2qb#81]
Paul Hermans has pointed out that the code imposes some default URI patterns in generated data, for example in the URIs of datasets and concept schemes, that follow the typical UK guidelines in URI styles.  However, the Flemish government has different standards, and it is not possible currently to configure table2qb to produce URIs in a different style.

**Comment by Robsteranium** [comment]
He reported that in #71 which was was merged into #69. I've extended that to include dataset/ dsd URIs too.
