### ISSUE TITLE
No documentation for the URIs created

### ISSUE THREAD

**Issue by zeginis** [Swirrl/table2qb#84]
A documentation of the URIs created by the pipelines is needed.
I have tried to document them here: https://github.com/Swirrl/graphql-qb/blob/master/doc/table2qb-cubiql.md

A documentation at the Table2qb page is also required.

**Comment by Robsteranium** [comment]
Thanks for this @zeginis.

@lkitching has added a new [usage page](https://github.com/Swirrl/table2qb/blob/master/doc/usage.md) which follows much the same flow as the example you've provided for the benefit of new users.

Thanks for the suggestions.
