### ISSUE TITLE
Provide ways to hide/redirect csvw metadata in output

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/table2qb#85]
e.g. we see lots of stuff like this...  I think because some of these pipelines are run with new data, the blank nodes and csvw:url's are growing at quite a rate... some of our datasets probably contain a few hundred, and counting at least.

<img width="1257" alt="screen shot 2018-11-07 at 22 02 39" src="https://user-images.githubusercontent.com/17060/48164072-68460500-e2d9-11e8-9b26-cd90788b7659.png">

I know this output is sometimes useful, so it might be worth trying to redirect into a different graph which we can optionally load.  Or maybe options for running in csvw minimal mode?

**Comment by Robsteranium** [comment]
We can't really use that audit data while it's full of blank nodes and references to temp files. Eventually it would be great to store the uploaded csvw and use this together with validations to point to broken cells etc. For now though, it's clutter.

Issue #96 would see us record all resource data in the csv tables, allowing us to use minimal mode.

In the mean time we need to use the custom `annotated` mode from here https://github.com/Swirrl/csv2rdf/issues/17.

**Comment by Robsteranium** [comment]
Fixed with #104.
